# Generated by Django 6.0.1 on 2026-01-28 11:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hostel_type', models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Sharing'), ('quad', 'Quad Sharing'), ('special', 'Special Room'), ('apartment', 'Apartment Style')], max_length=20)),
                ('location', models.CharField(choices=[('main_campus', 'Main Campus'), ('hill_side', 'Hill Side'), ('valley_road', 'Valley Road'), ('town_campus', 'Town Campus'), ('off_campus', 'Off Campus (Nearby)')], max_length=50)),
                ('address', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('price_per_semester', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_rooms', models.PositiveIntegerField()),
                ('rooms_available', models.PositiveIntegerField()),
                ('warden_name', models.CharField(blank=True, max_length=100)),
                ('warden_contact', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('has_wifi', models.BooleanField(default=False)),
                ('has_kitchen', models.BooleanField(default=False)),
                ('has_laundry', models.BooleanField(default=False)),
                ('has_shower', models.BooleanField(default=False)),
                ('has_pool', models.BooleanField(default=False)),
                ('has_gym', models.BooleanField(default=False)),
                ('has_study_room', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_security', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_phone', models.CharField(max_length=20)),
                ('student_id', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=50)),
                ('room_preference', models.CharField(blank=True, max_length=50)),
                ('special_requests', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hostels.hostel')),
            ],
            options={
                'ordering': ['-booked_at'],
            },
        ),
        migrations.CreateModel(
            name='HostelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hostel_images/')),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hostels.hostel')),
            ],
            options={
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
    ]
